# Generated by Django 4.2.16 on 2024-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_image_alter_cartitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MRP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
