# Generated by Django 4.2.16 on 2024-12-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('c', 'Cash'), ('o', 'Online')], default='c', max_length=10, null=True),
        ),
    ]
